force-app/main/default/objects/Car__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastAddedExpenseValue__c.field-meta.xml
<CustomField>
    <fullName>LastAddedExpenseValue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>LastAddedExpenseValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CarTriggerUtility.cls
public with sharing class CarTriggerUtility {
    public static void afterInsert(List<Car__c> cars){
        System.debug('utilitydebug');
        List<Contact> listOfChangedContacts= new List<Contact>();
        List<Contact> contacts = new List<Contact>();
        
        contacts= [SELECT Id,Expenses__c,LastAddedExpenseValue__c FROM Contact];

        for(Car__c	 car: cars){
            for(Contact contact: contacts){
                if(car.Contact__c==contact.id){
                    System.debug('Found Contact of Car');
                    contact.LastAddedExpenseValue__c= car.Price__c;
                    contact.Expenses__c+= car.Price__c;


                    listOfChangedContacts.add(contact);
                    }
            }
        }
    
        update listOfChangedContacts;
        System.debug('End CarTriggerUtility');
    

    }




    public static void beforeUpdate(List<Car__c> cars){
    






    }





    public static void beforeDelete(List<Car__c> cars){




    }
}