force-app/main/default/objects/Account/fields/NumberOfBoughtCars__c.field-meta.xml
<CustomField>
    <fullName>NumberOfBoughtCars__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NumberOfBoughtCars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wallet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastAddedExpenseValue__c.field-meta.xml
<CustomField>
    <fullName>LastAddedExpenseValue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>LastAddedExpenseValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContactTriggerExpensesService.cls
public with sharing class ContactTriggerExpensesService {
    public static List<Account> CheckingIsTheirExpensesChange(List<Contact> newTrigger,Map<ID, Contact> oldTrigger,Map<ID, Account> allAccounts){
         System.debug('CheckingIsTheirExpensesChange');
        List<Contact> contactForNextStep=new List<Contact>();
        for(Contact contactNew:newTrigger){
            if(contactNew.Expenses__c!=oldTrigger.get(contactNew.id).Expenses__c){
                System.debug('CheckingIsTheirExpensesChange if reached');
                contactForNextStep.add(contactNew);
            }
        }
        return preparingAccountsForUpdateAfterExpensesChange(allAccounts, contactForNextStep);
    
    }
    
    
    public static List<Account> preparingAccountsForUpdateAfterExpensesChange(Map<ID, Account> allAccounts,List<Contact> contactForNextStep){
        System.debug('preparingAccountsForUpdate');
        List<Account> accountsForUpdate=new List<Account>();
        for(Contact contact:contactForNextStep){
                Account account=allAccounts.get(contact.AccountId);
                if(account.NumberOfBoughtCars__c==0){
                        System.debug('Number of BoughtCars is 0 before trigger');
                        account.Wallet__c=account.Budget__c;
                    }
                System.debug('preparingAccountsForUpdate s for reached');
                account.Wallet__c-=contact.LastAddedExpenseValue__c;
                account.NumberOfBoughtCars__c++;
                accountsForUpdate.add(account);
        }   
        return accountsForUpdate;
                
    }   

}